# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(234, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.txtOrder = QtWidgets.QLineEdit(self.centralwidget)
        self.txtOrder.setInputMask("")
        self.txtOrder.setObjectName("txtOrder")
        self.horizontalLayout.addWidget(self.txtOrder)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txtAlpha = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAlpha.setObjectName("txtAlpha")
        self.horizontalLayout_2.addWidget(self.txtAlpha)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.txtA = QtWidgets.QLineEdit(self.centralwidget)
        self.txtA.setObjectName("txtA")
        self.horizontalLayout_4.addWidget(self.txtA)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.txtB = QtWidgets.QLineEdit(self.centralwidget)
        self.txtB.setObjectName("txtB")
        self.horizontalLayout_5.addWidget(self.txtB)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.txtNPart = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNPart.setObjectName("txtNPart")
        self.horizontalLayout_3.addWidget(self.txtNPart)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.calculateRootsButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateRootsButton.setObjectName("calculateRootsButton")
        self.verticalLayout.addWidget(self.calculateRootsButton)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_IterationNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_IterationNumber.setObjectName("label_IterationNumber")
        self.verticalLayout.addWidget(self.label_IterationNumber)
        self.btnResetIteration = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetIteration.setObjectName("btnResetIteration")
        self.verticalLayout.addWidget(self.btnResetIteration)
        self.btnNextIteration = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextIteration.setEnabled(False)
        self.btnNextIteration.setObjectName("btnNextIteration")
        self.verticalLayout.addWidget(self.btnNextIteration)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 234, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Draw the polynomials"))
        self.label_2.setText(_translate("MainWindow", "n="))
        self.txtOrder.setText(_translate("MainWindow", "30"))
        self.label_3.setText(_translate("MainWindow", "alpha= "))
        self.txtAlpha.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "a= "))
        self.txtA.setText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "b= "))
        self.txtB.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "n_part= "))
        self.txtNPart.setText(_translate("MainWindow", "15"))
        self.calculateRootsButton.setText(_translate("MainWindow", "Draw polynomials and roots"))
        self.label_IterationNumber.setText(_translate("MainWindow", "Iteration number = 0"))
        self.btnResetIteration.setText(_translate("MainWindow", "Reset iterations"))
        self.btnNextIteration.setText(_translate("MainWindow", "Next iteration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
